### ISSUE TITLE
Haxe nodes which extend godot.Node do not receive _ready/_process events

### ISSUE THREAD

**Issue by Greg209** [HxGodot/hxgodot#31]
Since 73e666ebf659ff403f86e76e619f441dc3643e3e (I believe), Haxe nodes in a project are not receiving _ready/_process events and so don't function. 

Trying Squash The Creeps, with commits after the one above, justs sits there not doing much - no Haxe interaction. Using the commit above gets it back working again.

**Comment by dazKind** [comment]
Fixed in https://github.com/HxGodot/hxgodot/commit/ef148b009909a6442b13bc57a8800abf47e28a97
