### ISSUE TITLE
Godot Crashes when exporting NodePaths

### ISSUE THREAD

**Issue by drflamemontgomery** [HxGodot/hxgodot#47]
I've noticed that if you try to export a NodePath it will throw an error when opening the Godot project in Godot.

I have my example code below
```haxe
package;

class TestClass extends godot.Node {

  // When the line below is removed, Godot doesn't crash
  @:export public var test_export(default, default) : godot.variant.NodePath;

  public function new() {
    super();
  }

}
```

When I open the project in Godot I get the message
```
terminate called after throwing an instance of 'Dynamic
```

**Comment by drflamemontgomery** [comment]
Just figured out that I have to initialize the NodePath by using 'new NodePath()'

for anyone else who is having trouble, this is the fixed code

```haxe
package;

class TestClass extends godot.Node {

  @:export public var test_export(default, default) : godot.variant.NodePath = new godot.variant.NodePath();

  public function new() {
    super();
  }

}
```

**Comment by dazKind** [comment]
Yes, that's a requirement, otherwise your property is null. You either do it like you did or you do it in the constructor of your class (if you have one)
