### ISSUE TITLE
How to debug example

### ISSUE THREAD

**Issue by takhimi** [HxGodot/hxgodot#50]
In the debugging section of the readme, you mention this "<path to godot binary> -e --path <included test project folder>" 
can you please provide example of vscode launch.json on how to debug the codes. Sorry for my lack of knowledge on this matter. I think it would be really great if you provide the example on how to set it up.
Thanks

**Comment by dazKind** [comment]
I debug using Visual Studio. Sadly I'm not a VSCode user. So you might wanna look at the Godot Documentation on building and debugging.

**Comment by dazKind** [comment]
I just stumbled upon a video where a launch.json is setup for a gdextension. This might help you getting it to work: https://www.twitch.tv/videos/1733992017?t=0h19m40s

**Comment by takhimi** [comment]
Awesome. Thank you!
