### ISSUE TITLE
Set output directory for scenes

### ISSUE THREAD

**Issue by AngelODeath** [HxGodot/hxgodot#56]
I'm currently working with your GitHub repository and I have a question regarding setting the output directory for the generated scenes. Apologies if this information is available somewhere, but I couldn't find it in the documentation.

I would like to specify a custom output path for the scenes that are generated by the application. Ideally, I would like to direct them to a dedicated "scenes" folder. Could you please guide me on how to achieve this? If there are any configuration settings or code modifications required, I would appreciate some instructions or pointers.

Thank you for your assistance!

**Comment by dazKind** [comment]
Hi there, as for the organization of your project and the key-concepts around Godot's scenes I can only refer you to the official Godot Documentation: https://docs.godotengine.org/en/stable/getting_started/step_by_step/nodes_and_scenes.html
