### ISSUE TITLE
scons build is failing

### ISSUE THREAD

**Issue by alexeychikk** [HxGodot/hxgodot#60]
`scons platform=windows target=debug ` is failing for me
Reproducible here https://github.com/alexeychikk/hx-godot-squash-the-creeps
Haxe 4.3.3
The error is:
```
Error: World2D.cpp
./src/godot/World2D.cpp(409): error C2039: 'gdextension_interface_object_free_instance_binding': is not a member of 'godot::internal'
C:\Users\alexd\AppData\Roaming\haxe\haxelib\hxgodot\git\src\godot_cpp/godot.hpp(38): note: see declaration of 'godot::internal'
./src/godot/World2D.cpp(409): error C3861: 'gdextension_interface_object_free_instance_binding': identifier not found  
```

**Comment by alexeychikk** [comment]
When I roll back `hxgodot` to `021911de05bbee848c643c441981331fd014bb1e` - it doesn't fail anymore.

**Comment by dazKind** [comment]
I dont quite understand? 

It should be defined there: 
- https://github.com/HxGodot/hxgodot/blame/main/src/godot_cpp/godot.cpp#L162 
- https://github.com/HxGodot/hxgodot/blob/main/src/godot_cpp/godot.hpp#L160

**Comment by alexeychikk** [comment]
My bad, I was using lix and haxelib at the same time. scons was using the old version from haxelib
